### ISSUE TITLE
Remplacer "Page x de y" par "Page x sur y" (au bas des pages)

### ISSUE THREAD

**Issue by quark67** [jejust/visualFAQ-fr#2]
Il me semble que l'expression "Page x **sur** y" est plus française que "Page x **de** y".

D'ailleurs c'est bien l'expression "sur" qui est employée à l'adresse https://faq.gutenberg.eu.org/3_composition/texte/pages/numerotation_des_pages/numeroter_les_pages_avec_k_sur_n.

**Comment by jejust** [comment]
Merci, c'est corrigé dans le dépôt Git (pas encore sur CTAN).
